---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: monitoring
  labels:
    app: elasticsearch
    component: monitoring
    part-of: membo-ai
spec:
  type: ClusterIP
  ports:
    - name: elasticsearch-rest
      port: 9200
      targetPort: 9200
      protocol: TCP
    - name: elasticsearch-transport
      port: 9300
      targetPort: 9300
      protocol: TCP
  selector:
    app: elasticsearch
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elasticsearch
  namespace: monitoring
  labels:
    app: elasticsearch
    component: monitoring
    part-of: membo-ai
spec:
  replicas: 3
  serviceName: elasticsearch
  selector:
    matchLabels:
      app: elasticsearch
  updateStrategy:
    type: RollingUpdate
  podManagementPolicy: Parallel
  template:
    metadata:
      labels:
        app: elasticsearch
        component: monitoring
        part-of: membo-ai
    spec:
      securityContext:
        fsGroup: 1000
        runAsUser: 1000
      initContainers:
        - name: fix-permissions
          image: busybox:1.35
          command: ["sh", "-c", "chown -R 1000:1000 /usr/share/elasticsearch/data"]
          volumeMounts:
            - name: elasticsearch-data
              mountPath: /usr/share/elasticsearch/data
        - name: increase-vm-max-map
          image: busybox:1.35
          command: ["sysctl", "-w", "vm.max_map_count=262144"]
          securityContext:
            privileged: true
        - name: configure-sysctl
          image: busybox:1.35
          command: ["sh", "-c", "ulimit -n 65536"]
          securityContext:
            privileged: true
      containers:
        - name: elasticsearch
          image: docker.elastic.co/elasticsearch/elasticsearch:8.11.1
          env:
            - name: node.name
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: ZONE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['topology.kubernetes.io/zone']
            - name: cluster.name
              value: membo-monitoring
            - name: discovery.type
              value: kubernetes
            - name: discovery.seed_hosts
              value: "elasticsearch-0.elasticsearch.monitoring.svc.cluster.local,elasticsearch-1.elasticsearch.monitoring.svc.cluster.local,elasticsearch-2.elasticsearch.monitoring.svc.cluster.local"
            - name: cluster.initial_master_nodes
              value: "elasticsearch-0,elasticsearch-1,elasticsearch-2"
            - name: ES_JAVA_OPTS
              value: "-Xms2g -Xmx2g -XX:+UseG1GC -XX:G1ReservePercent=25 -XX:InitiatingHeapOccupancyPercent=30"
            - name: bootstrap.memory_lock
              value: "true"
            - name: xpack.security.enabled
              value: "true"
            - name: xpack.monitoring.collection.enabled
              value: "true"
            - name: ELASTIC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: ELASTIC_PASSWORD
          ports:
            - name: rest
              containerPort: 9200
              protocol: TCP
            - name: transport
              containerPort: 9300
              protocol: TCP
          resources:
            requests:
              cpu: 1000m
              memory: 2Gi
              ephemeral-storage: 1Gi
            limits:
              cpu: 2000m
              memory: 4Gi
              ephemeral-storage: 2Gi
          volumeMounts:
            - name: elasticsearch-data
              mountPath: /usr/share/elasticsearch/data
            - name: elasticsearch-certs
              mountPath: /usr/share/elasticsearch/config/certs
              readOnly: true
            - name: elasticsearch-config
              mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
              subPath: elasticsearch.yml
            - name: jvm-config
              mountPath: /usr/share/elasticsearch/config/jvm.options
              subPath: jvm.options
          readinessProbe:
            httpGet:
              scheme: HTTPS
              path: /_cluster/health?local=true
              port: 9200
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              scheme: HTTPS
              path: /_cluster/health?local=true
              port: 9200
            initialDelaySeconds: 120
            periodSeconds: 20
            timeoutSeconds: 5
      volumes:
        - name: elasticsearch-config
          configMap:
            name: membo-config
            items:
              - key: elasticsearch.yml
                path: elasticsearch.yml
        - name: jvm-config
          configMap:
            name: membo-config
            items:
              - key: jvm.options
                path: jvm.options
        - name: elasticsearch-certs
          secret:
            secretName: app-secrets
            items:
              - key: elasticsearch.key
                path: elasticsearch.key
                mode: 384
              - key: elasticsearch.crt
                path: elasticsearch.crt
                mode: 420
              - key: ca.crt
                path: ca.crt
                mode: 420
  volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: premium-rwo
        resources:
          requests:
            storage: 100Gi