# Metricbeat DaemonSet configuration for membo.ai infrastructure monitoring
# Version: 8.11.1

apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: metricbeat
  namespace: monitoring
  labels:
    app: metricbeat
    component: monitoring
spec:
  selector:
    matchLabels:
      app: metricbeat
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: metricbeat
    spec:
      serviceAccountName: metricbeat
      terminationGracePeriodSeconds: 30
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: metricbeat
        image: docker.elastic.co/beats/metricbeat:8.11.1
        args: [
          "-c", "/usr/share/metricbeat/metricbeat.yml",
          "-e",
        ]
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: ELASTIC_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: ELASTIC_PASSWORD
        securityContext:
          runAsUser: 0
          privileged: true
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
        volumeMounts:
        - name: config
          mountPath: /usr/share/metricbeat/metricbeat.yml
          subPath: metricbeat.yml
        - name: metricbeat-certs
          mountPath: /usr/share/metricbeat/config/certs
          readOnly: true
        - name: proc
          mountPath: /hostfs/proc
          readOnly: true
        - name: cgroup
          mountPath: /hostfs/sys/fs/cgroup
          readOnly: true
        - name: dockersock
          mountPath: /var/run/docker.sock
          readOnly: true
      volumes:
      - name: config
        configMap:
          name: metricbeat-config
          items:
            - key: metricbeat.yml
              path: metricbeat.yml
      - name: metricbeat-certs
        secret:
          secretName: app-secrets
          items:
          - key: metricbeat.crt
            path: metricbeat.crt
          - key: metricbeat.key
            path: metricbeat.key
          - key: ca.crt
            path: ca.crt
      - name: proc
        hostPath:
          path: /proc
      - name: cgroup
        hostPath:
          path: /sys/fs/cgroup
      - name: dockersock
        hostPath:
          path: /var/run/docker.sock
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: metricbeat-config
  namespace: monitoring
  labels:
    app: metricbeat
data:
  metricbeat.yml: |
    setup.kibana.host: "kibana:5601"
    setup.template.settings:
      index.number_of_replicas: 1
    
    logging.level: info
    logging.metrics.enabled: true
    
    metricbeat.modules:
    - module: system
      metricsets:
        - cpu
        - load
        - memory
        - network
        - process
        - filesystem
        - fsstat
        - uptime
      period: 10s
      enabled: true
      processes: ['.*']
      
    - module: kubernetes
      metricsets:
        - container
        - node
        - pod
        - system
        - volume
        - state_container
        - state_pod
        - state_node
      period: 30s
      enabled: true
      hosts: ['https://${NODE_NAME}:10250']
      bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
      ssl.verification_mode: none
      add_metadata: true
    
    output.elasticsearch:
      hosts: ['https://elasticsearch:9200']
      username: elastic
      password: ${ELASTIC_PASSWORD}
      ssl:
        enabled: true
        certificate_authorities: ["/usr/share/metricbeat/config/certs/ca.crt"]
        certificate: "/usr/share/metricbeat/config/certs/metricbeat.crt"
        key: "/usr/share/metricbeat/config/certs/metricbeat.key"
---
apiVersion: v1
kind: Service
metadata:
  name: metricbeat-monitoring
  namespace: monitoring
  labels:
    app: metricbeat
spec:
  type: ClusterIP
  ports:
    - name: monitoring
      port: 5066
      targetPort: 5066
      protocol: TCP
  selector:
    app: metricbeat
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: metricbeat
  labels:
    app: metricbeat
rules:
- apiGroups: [""]
  resources:
    - nodes
    - namespaces
    - events
    - pods
  verbs: ["get", "list", "watch"]
- apiGroups: ["extensions"]
  resources:
    - replicasets
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources:
    - statefulsets
    - deployments
    - replicasets
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources:
    - nodes/stats
  verbs: ["get"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: metricbeat
  namespace: monitoring
  labels:
    app: metricbeat
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: metricbeat
subjects:
- kind: ServiceAccount
  name: metricbeat
  namespace: monitoring
roleRef:
  kind: ClusterRole
  name: metricbeat
  apiGroup: rbac.authorization.k8s.io