# Prometheus Server Configuration v2.45.0
# Defines monitoring targets, scrape intervals, alerting rules and storage settings
# for membo.ai monitoring infrastructure

apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring
  labels:
    app: membo
    component: monitoring
data:
  prometheus.yml: |
    # Global configuration
    global:
      scrape_interval: 15s     # How frequently to scrape targets
      evaluation_interval: 15s  # How frequently to evaluate rules
      scrape_timeout: 10s      # Timeout for scrape requests

    # Scrape configurations
    scrape_configs:
      # Backend service monitoring
      - job_name: 'membo-backend'
        kubernetes_sd_configs:
          - role: pod
            namespaces:
              names: ['membo']
            selectors:
              - role: pod
                label: 'app=membo,component=backend'
        
        metrics_path: /metrics
        scheme: http
        
        # Relabeling configurations
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_label_app]
            target_label: app
          - source_labels: [__meta_kubernetes_pod_label_component]
            target_label: component

    # Alerting rules
    rule_files:
      - /etc/prometheus/rules/*.yml

    # Alerting rules definitions
    alerting_rules:
      # API Latency monitoring
      - name: HighLatency
        rules:
          - alert: APIHighLatency
            expr: http_request_duration_seconds > 0.2
            for: 5m
            labels:
              severity: warning
            annotations:
              summary: High API latency detected
              description: API endpoint response time exceeds 200ms threshold

      # System Uptime monitoring
      - name: SystemUptime
        rules:
          - alert: LowUptime
            expr: avg_over_time(up[24h]) < 0.999
            for: 5m
            labels:
              severity: critical
            annotations:
              summary: System uptime below SLA
              description: System availability is below 99.9% threshold

      # AI Processing monitoring  
      - name: AIProcessing
        rules:
          - alert: SlowAIProcessing
            expr: ai_processing_duration_seconds > 10
            for: 5m
            labels:
              severity: warning
            annotations:
              summary: Slow AI processing detected
              description: AI card generation taking longer than 10 seconds

    # Storage configuration
    storage:
      tsdb:
        # 15 days retention with 50GB size limit
        retention_time: 15d
        retention_size: 50GB
        # Directory for TSDB storage
        path: /prometheus

    # Remote write/read endpoints can be added here for long-term storage
    # remote_write:
    # remote_read: