apiVersion: v1
kind: ConfigMap
metadata:
  name: membo-config
  namespace: membo
  labels:
    app: membo
    environment: production
data:
  # Server Configuration
  NODE_ENV: "production"
  PORT: "4000"
  LOG_LEVEL: "info"
  
  # Database Connection Pool Settings
  DB_POOL_MIN: "2"
  DB_POOL_MAX: "10"
  DB_TIMEOUT: "30000"
  
  # Redis Cache Configuration
  REDIS_TTL: "900"
  REDIS_MAX_RETRIES: "3"
  
  # API Rate Limiting
  RATE_LIMIT_WINDOW: "900000"
  RATE_LIMIT_MAX: "100"
  JWT_EXPIRY: "30m"
  
  # Monitoring and Observability
  METRICS_ENABLED: "true"
  TRACING_ENABLED: "true"
  
  # HTTP Configuration
  REQUEST_TIMEOUT: "5000"
  CORRELATION_HEADER: "x-correlation-id"
  MAX_PAYLOAD_SIZE: "5mb"
  COMPRESSION_ENABLED: "true"
  
  # API Configuration
  API_VERSION: "v1"
  
  # Health Checks
  HEALTH_CHECK_PATH: "/health"
  READINESS_CHECK_PATH: "/ready"