apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: membo
  annotations:
    kubernetes.io/created-by: membo-platform
    encryption.membo.ai/type: aes-256-gcm
    rotation.membo.ai/schedule: 90-days
    backup.membo.ai/policy: daily-encrypted
type: Opaque
data:
  # OpenAI API key for AI-powered card generation and content processing
  # Rotation: 90 days, Used by: backend
  OPENAI_API_KEY: <base64_encoded_value>

  # Supabase configuration for database and auth services
  # Rotation: never for URL, 90 days for keys
  # Used by: backend + web (URL and anon key only)
  SUPABASE_URL: <base64_encoded_value>
  SUPABASE_SERVICE_KEY: <base64_encoded_value>
  SUPABASE_ANON_KEY: <base64_encoded_value>

  # JWT secret for session management
  # Rotation: 90 days, Used by: backend
  JWT_SECRET: <base64_encoded_value>

  # Redis authentication for caching
  # Rotation: 90 days, Used by: backend
  REDIS_PASSWORD: <base64_encoded_value>

  # Stripe configuration for payments
  # Rotation: 90 days, Used by: backend
  STRIPE_SECRET_KEY: <base64_encoded_value>

  # Encryption keys for sensitive data
  # Rotation: 90 days, Used by: backend
  ENCRYPTION_KEY: <base64_encoded_value>
  BACKUP_ENCRYPTION_KEY: <base64_encoded_value>